apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app
  labels:
    name: vote-app
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vote-app
      app: demo-voting-app
  template:
    metadata:
      name: vote-app
      labels:
        name: vote-app
        app: demo-voting-app
    spec:
      containers:
        - name: vote-app
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80