apiVersion: v1
kind: Service
metadata:
  name: vote-app
  labels:
    name: vote-app
    app: demo-voting-app
spec:
  type: LoadBalancer
  selector:
    name: vote-app
    app: demo-voting-app
  ports:
    - port: 80
      targetPort: 80