apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-db
    app: demo-voting-app
spec:
  type: ClusterIP
  selector:
    name: postgres-db
    app: demo-voting-app
  ports:
    - port: 5432