apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis
    app: demo-voting-app
spec:
  type: ClusterIP
  selector:
    name: redis
    app: demo-voting-app
  ports:
    - port: 6379
      targetPort: 6379