apiVersion: v1
kind: Service
metadata:
  name: result-app
  labels:
    name: result-app
    app: demo-voting-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    name: result-app
    app: demo-voting-app
  ports:
    - port: 80
      targetPort: 80